% setup for the final pdf document

\usepackage[margin=2cm]{geometry}
% delete renew command for \includegraphics

% do search replace for widths > make (say) 6cm \includegraphics[width=6cm]

% replace "plot of chunk " with ""

\author{
   Cheshire, James\\
  \texttt{james.cheshire@ucl.ac.uk}
  \and
  Lovelace, Robin\\
  \texttt{r.lovelace@leeds.ac.uk}
}
\title{Introduction to Spatial Data and ggplot2}

\maketitle 

\pagestyle{myheadings}
\markboth{\hfill }{GeoTALISMAN Short Course \hfill}
