---
  title: "Aerial photos in R"
author: "Robin Lovelace"
date: "30/07/2014"
output: html_document
---
  
```{r}
library(ggmap)
library(raster)
gc <- as.numeric(geocode("Norton Canon"))
ggmap(get_map(location = gc))
gm <- get_map(location = gc, zoom = 20)
ggmap(gm)
gm <- get_map("Norton Canon", zoom = 17, maptype = "satellite")
ggmap(gm) 
# ggmap(get_googlemap("Norton Canon", zoom = 19, maptype = "satellite", size = c(640,640), scale = 2))
gr1 <- ggmap_rast(map = gm)
class(gr1)
(bb <- bbox(gr1))
# but how to save as geotiff?
```

```{r}
bb2 <- bb
bb2[1, ] <- bb[1, ] + (bb[1, 2] - bb[1, 1])
gm2 <- get_map(bb2, maptype = "satellite")
ggmap(gm2)
gr2 <- ggmap_rast(gm2)
gr3 <- raster::merge(gr1, gr2, tolerance = 1)
plot(gr3)
raster::plotRGB(gr3)
```

Now generalise the solution:
  
```{r}
n_row <- 2
n_col <- 2
bb_array <- array(NA, dim = c(2, 2, n_row, n_col))
bb_array[1,,1,1] <- bb[1, ] - (n_col / 2) * (bb[1, 2] - bb[1, 1])  # top left x
bb_array[2,,1,1] <- bb[1, ] - (n_row / 2) * (bb[2, 2] - bb[2, 1])  # top left y
for(i in 1:n_col){
  for(j in 1:n_row){
    bb_array[1,,j,i] <- bb[1, ] - (n_col / 2) * (bb[1, 2] - bb[1, 1]) + (j - 1)* (bb[1, 2] - bb[1, 1])  
    bb_array[2,,j,i] <- bb[2, ] - (n_col / 2) * (bb[2, 2] - bb[2, 1]) + (i - 1)* (bb[2, 2] - bb[2, 1])  
  }
}

plot(bb_array)

ggmap(get_map(bb_array[,,2,1])) # check they are the same
ggmap(get_map(bb_array[,,2,2]))

# save the files
grm <- ggmap_rast(get_map(bb_array[,,1,1], maptype = "satellite"))
for(i in 1:n_col){
  for(j in 1:n_row){    
    gr <- ggmap_rast(get_map(bb_array[,,j,i], maptype = "satellite"))
    grm <- raster::merge(gr, grm, tolerance = 1)
  }
}
plotRGB(grm)
writeRaster(grm, filename = "~/Dropbox/Public/tmp/google-raster-4.tif", 
            format="GTiff", overwrite = T)
```
