---
title: "Spatial Data with R: futureproof foundations"
author: "Robin Lovelace"
date: "2017-10-06"
output: github_document
---

# Description

This one day course will get you up-to-speed with using R and RStudio for daily working with spatial data.
You will learn about R's powerful geospatial data processing, analysis and visualisation capabilities.
It is practical and hands-on: you'll *learn by doing*.
It assumes you already use R and want to extend your knowledge for spatial data applications.
It will cover the recently developed **sf** package, which is compatible with the **tidyverse**, representing the cutting-edge of spatial data applications.
It will provide a solid foundation (including spatial aggregation, joining, CRSs, visualisation) on which advanced analysis analysis workflows can be built.

# Learning outcomes

By the end of the course participants will:

 - Understand R's spatial ecosystem and which packages are 'future proof'
 - Know how to optimise RStudio for productive working with spatial data (you should already be proficient with RStudio)
 - Be able to read and write a variety of spatial data formats
 - Be proficient at common spatial operations including subsetting, cropping, aggregation and transformation
 - Be a confident map maker using the powerful **tmap** package
 - Know where to look for learning more advanced methods
 
## Prerequisites

In preparation for the course you should:

- Ensure that you have the latest versions of R and RStudio installed on your laptop: https://www.rstudio.com/products/rstudio/download/
- Brush up on your R skills if you're not an R user, e.g. with:
    - This excellent tutorial that you can work through to get used to the interface: https://www.datacamp.com/courses/free-introduction-to-r
    - A more detailed account by Gillespie and Lovelace (2017): https://csgillespie.github.io/efficientR/set-up.html#rstudio
- Take a look at how GitHub works - we'll be using it for sharing course materials and sharing links and examples during the course, e.g. by reading this page (and following the tutorial if really keen): https://guides.github.com/activities/hello-world/

You must have the following packages installed:

```{r, eval=FALSE}
install.packages("sf")
install.packages("tmap")
install.packages("spData")
```



## Course materials

The course will be based on Chapter 3 and 4 of [Geocomputation with R](http://robinlovelace.net/geocompr/attr.html) of the forethcoming book *Geocomputation with R* plus some additional materials:

- An introduction to geographic data in R
    - Chapter 2 of [Geocomputation with R](http://robinlovelace.net/geocompr/spatial-class.html)
- Geographic data I/O
    - Chapter 5 of [Geocomputation with R](http://robinlovelace.net/geocompr/read-write.html)
- Introduction to visualising spatial data with R
    - [Creating-maps-in-R](https://github.com/Robinlovelace/Creating-maps-in-R) GitHub tutorial
- Point pattern analysis and rasterization
    - [Point Pattern analysis and spatial interpolation with R
](https://github.com/Robinlovelace/Creating-maps-in-R/blob/master/vignettes/point-pattern.md) from the previous tutorial

## Course agenda

Refreshments & set-up: (09:00 - 09:30)

- R's spatial ecosystem: (09:30 - 09:40)
    - See section [1.4 of Geocomputation with R](http://robinlovelace.net/geocompr/intro.html#rs-spatial-ecosystem)
- R and RStudio for spatial data (09:40 - 09:50)
    - See [Section 2.5 of Efficient R Programming](https://csgillespie.github.io/efficientR/set-up.html#rstudio)
- An introduction to simple features (09:50 - 10:00)
    - See [Spatial Data and the tidyverse](http://robinlovelace.net/presentations/spatial-tidyverse.html#1)
- Working with attribute data (10:00 - 10:45)
    - [Section 3.2](http://robinlovelace.net/geocompr/attr.html#vector-attribute-manipulation) of handouts

Coffee break: (10:45 - 11:00)

- Raster data classes and functions (11:00 - 11:15)
    - Online tutorial: [2.2 of Geocomputation with R](http://robinlovelace.net/geocompr/spatial-class.html#raster-data)
    - OR continue with section 3.2
- Raster attribute data (11:15 - 12:00)
    - [Section 3.3](http://robinlovelace.net/geocompr/attr.html#manipulating-raster-objects) of handouts
- Free working (12:00 - 12:30)
    - Challenge: working-through and complete the exercises in Chapter 3
    - Bonus: ask a question and help explain something
    - Advanced: look into GitHub and datascience

LUNCH and looking at your data (12:30 - 13:30)
 
- Worked example: car fleet analysis with Craig Morton (13:30 - 14:15)

- Spatial data operations (14:15 - 15:00)
    - Practical based on the second handout
    - Spatial subsetting, section 4.2.1
    - Topological relations
    - Spatial joining and aggregation

Coffee break: 15:00 - 15:15

- Geographic data I/O: (15:15 - 15:30)
    - Taught lecture
    - Test based on your own data
- Spatial operations on raster data (15:30 - 15:45)
    - Practical - work through section 4.3

- Consolidating knowledge (15:45 - 16:15)
    - Completing the printed hand-out OR
    - Point pattern analysis, interpolation and rasterization [tutorial](https://github.com/Robinlovelace/Creating-maps-in-R/blob/master/vignettes/point-pattern.md)
    - Working on your own data
    
- Wrap-up and next steps (16:15 - 16:30)


