# R for Spatial Data: Futureproof foundations

- 6 October 2017

This document provides a how for the course on 2017-10-06 in LIDA Leeds.

It is primarily intended to provide a set of links for course participants but can also host code examples and notes from the workshop.

## Slides

- See the 'slides' folder in for the text: [github.com/Robinlovelace/geocompr](https://github.com/Robinlovelace/geocompr/blob/master/slides/)
- For compiled slides on Spatial Data and the Tidyverse see [robinlovelace.net/presentations/spatial-tidyverse.html](http://robinlovelace.net/presentations/spatial-tidyverse.html#1)

## Links

- Agenda  and other course details on GitHub at [course-info/intro-info.Rmd](https://github.com/Robinlovelace/Creating-maps-in-R/blob/master/course-info/intro-info.Rmd)
- [Geocomputation with R](http://robinlovelace.net/geocompr/)

- An introduction to geographic data in R
    - Chapter 2 of [Geocomputation with R](http://robinlovelace.net/geocompr/spatial-class.html)
- Geographic data I/O
    - Chapter 5 of [Geocomputation with R](http://robinlovelace.net/geocompr/read-write.html)
- Introduction to visualising spatial data with R
    - [Creating-maps-in-R](https://github.com/Robinlovelace/Creating-maps-in-R) GitHub tutorial
- Point pattern analysis and rasterization
    - [Point Pattern analysis and spatial interpolation with R
](https://github.com/Robinlovelace/Creating-maps-in-R/blob/master/vignettes/point-pattern.md) from the previous tutorial